#!/bin/bash
#
# =================================================================================================
# RLum.CHECK_AND_BUILD shell script
# author: R Luminescence Team
# date: 2019-01-05
#
# Customized R check and build routine for the R package 'Luminescence'
# =================================================================================================
#
#
# CONFIG AND DEFINITIONS
# =================================================================================================
#
export TERM=xterm
PATHPACKAGE=$(dirname $0)

#
check_status(){
  if [ $? == 0 ]; then
    echo "[OK]"
  else
    echo "[FAILED]"
  fi
}
#
#
# REMOVING UNWANTED FILES
# =================================================================================================
echo ""
echo -ne "Set package path to " ${PATHPACKAGE} "\n\n"
echo "[PREPARE FOR PACKAGE CHECK]"
echo ""
#

  echo -ne "-> Clean RLum.BuildResults folder ... \t\t"
  find ${PATHPACKAGE}/RLum.BuildResults -type f -exec rm {} \;
  check_status

  echo -ne "-> Remove .DS_Store ... \t\t\t"
  find ${PATHPACKAGE} -name ".DS_Store" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .Rhistory ... \t\t\t"
  find ${PATHPACKAGE} -name ".Rhistory" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .RData ... \t\t\t\t"
  find ${PATHPACKAGE} -name ".RData" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .RcppExports.cpp ... \t\t\t"
  find ${PATHPACKAGE}/src -name "RcppExports.cpp" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .RcppExports.R ... \t\t\t"
  find ${PATHPACKAGE}/R -name "RcppExports.R" -depth -exec rm {} \;
  check_status

# Rcpp
# =================================================================================================
  echo -ne "-> Build Rcpp ... \t\t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_Rcpp.R /dev/null
  check_status


# REMOVE NAMESPACE
# =================================================================================================
  echo -ne "-> Remove NAMESPACE ... \t\t\t"
  find ${PATHPACKAGE} -name "NAMESPACE" -depth -exec rm {} \;
  check_status


# roxygen2
# =================================================================================================
  echo -ne "-> Create empty NAMESPACE file... \t\t"
  echo '# Generated by roxygen2 (6.1.1): do not edit by hand' > NAMESPACE
  check_status

  echo -ne "-> Build documentation ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_roxygen2.R /dev/null
  check_status

# set date and version number
# =================================================================================================
  echo -ne "-> Update date and version number ... \t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_VersionNumber.R /dev/null
  check_status


# Set entry points
# =================================================================================================
  echo -ne "-> Set entry points ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_EntryPointRegistration.R /dev/null
  check_status

#
# NEWS
# =================================================================================================

  echo -ne "-> Knit NEWS ... \t\t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_knit_NEWS.R /dev/null
  check_status
#
# PARSE RD files and add RLum.Team
# =================================================================================================

  echo -ne "-> Add RLum.Team ... \t\t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_AddRLumTeam.R /dev/null
  check_status

#
# PARSE RD files and add function citation
# =================================================================================================

  #this pause is needed, otherwise the first files might not be accessed correctly
  sleep 2
  echo -ne "-> Add 'How to cite' section ... \t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_Citation.R /dev/null
  check_status

#
# BUILD PACKAGE
# =================================================================================================
echo ""
echo "[BUILD PACKAGE]"
echo ""

  eval R CMD build ${PATHPACKAGE}


#
# CHECK PACKAGE
# =================================================================================================
echo ""
echo "[CHECK PACKAGE]"
echo ""

  VERSION=$(cat DESCRIPTION | grep Version: | awk '/Version/ {print substr($0, 10)}')
  eval R CMD check --timings --as-cran ${PATHPACKAGE}/Luminescence_${VERSION}.tar.gz
  #eval R CMD check --timings ${PATHPACKAGE}/Luminescence_${VERSION}.tar.gz

  #eval R CMD check --timings ${PATHPACKAGE}/Luminescence*.tar.gz

  echo -ne 'Example timing warnings...:\n\n'
  eval R CMD BATCH ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_Timings.R /dev/null
  cat ${PATHPACKAGE}/RLum.BuildResults/Luminescence-Ex.timings.*.WARNING


#
# INSTALL PACKAGE
# =================================================================================================
echo ""
echo "[INSTALL PACKAGE]"
echo ""

  eval R CMD INSTALL --build ${PATHPACKAGE}/Luminescence*.tar.gz

#
# COPY FILES AND CLEANING UP
# =================================================================================================
echo ""
echo "[OUTRO]"
echo ""

  echo -ne "-> Write BibTeX ... \t\t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_BibTeX.R /dev/null
  check_status

  echo -ne "-> Build function list ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_Function_List.R /dev/null
  check_status

#
# COMPILE FUNCTION PARAMETER LIST
# =================================================================================================

  echo -ne "-> Compile function argument list ...\t\t"
  eval R CMD BATCH ${PATHPACKAGE}/RLum.BuildScripts/RLum.PBS_Function_Arguments.R /dev/null
  check_status

  echo -ne "-> Moving packge source files (*.tar.gz) ... \t"
  mv Luminescence_*.tar.gz RLum.BuildResults/ &>/dev/null
  check_status

  echo -ne "-> Moving packge compiles package (*.tgz) ... \t"
  mv Luminescence_*.tgz RLum.BuildResults/ &>/dev/null
  check_status

  echo -ne "-> Copy manual ... \t\t\t\t"
  cp Luminescence.Rcheck/Luminescence-manual.pdf RLum.BuildResults/Luminescence-manual.pdf &>/dev/null
  check_status

  echo -ne "-> Copy check results ... \t\t\t"
  cp Luminescence.Rcheck/Luminescence-Ex.pdf RLum.BuildResults/Luminescence-Ex.pdf &>/dev/null
  check_status

  echo -ne "-> Remove Luminescence.Rcheck ... \t\t"
  rm -r ${PATHPACKAGE}/Luminescence.Rcheck &>/dev/null
  check_status

  echo -ne "-> Remove src/*.so ... \t\t\t\t"
  find ${PATHPACKAGE}/src -name "*.so" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove src/*.o ... \t\t\t\t"
  find ${PATHPACKAGE}/src -name "*.o" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove src/*.o* ... \t\t\t\t"
  find ${PATHPACKAGE}/src -name "*.o*" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove src/*.rds ... \t\t\t"
  find ${PATHPACKAGE}/src -name "*.rds" -depth -exec rm {} \;
  check_status

  echo ""
  echo "[FINE]"
