pkgname <- "BayLum"
source(file.path(R.home("share"), "R", "examples-header.R"))
options(warn = 1)
base::assign(".ExTimings", "BayLum-Ex.timings", pos = 'CheckExEnv')
base::cat("name\tuser\tsystem\telapsed\n", file=base::get(".ExTimings", pos = 'CheckExEnv'))
base::assign(".format_ptime",
function(x) {
  if(!is.na(x[4L])) x[1L] <- x[1L] + x[4L]
  if(!is.na(x[5L])) x[2L] <- x[2L] + x[5L]
  options(OutDec = '.')
  format(x[1L:3L], digits = 7L)
},
pos = 'CheckExEnv')

### * </HEADER>
library('BayLum')

base::assign(".oldSearch", base::search(), pos = 'CheckExEnv')
base::assign(".old_wd", base::getwd(), pos = 'CheckExEnv')
cleanEx()
nameEx("AgeC14_Computation")
### * AgeC14_Computation

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: AgeC14_Computation
### Title: Bayesian analysis for C-14 age estimations of various samples
### Aliases: AgeC14_Computation

### ** Examples

## Load data
data(DATA_C14,envir = environment())
C14Cal <- DATA_C14$C14[,1]
SigmaC14Cal <- DATA_C14$C14[,2]
Names <- DATA_C14$Names
nb_sample <- length(Names)

## Age computation of samples without stratigraphic relations
Age <- AgeC14_Computation(
 Data_C14Cal = C14Cal,
 Data_SigmaC14Cal = SigmaC14Cal,
 SampleNames = Names,
 Nb_sample = nb_sample,
 PriorAge = rep(c(20,60),nb_sample),
 Iter = 500,
 quiet = TRUE,
 roundingOfValue = 3)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("AgeC14_Computation", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("AgeS")
### * AgeS

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: AgeS
### Title: Output of 'AgeS_Computation' function for the samples: "GDB5"
###   and "GDB3"
### Aliases: AgeS
### Keywords: datasets

### ** Examples

data(AgeS)
str(AgeS)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("AgeS", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("AgeS_Computation")
### * AgeS_Computation

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: AgeS_Computation
### Title: Bayesian analysis for OSL age estimation of various samples
### Aliases: AgeS_Computation

### ** Examples

## Age computation of samples GDB5 and GDB3,
## load data
data(DATA2) # GD85
data(DATA1) # GD83

## produce DataFile
Data <- combine_DataFiles(DATA2, DATA1)

## without common error, assuming GDB5 age younger than GDB3 age
Nb_sample <- 2
SC <- matrix(
  data = c(1,1,0,1,0,0),
  ncol = 2,
  nrow = (Nb_sample+1),
  byrow = TRUE)

## Not run: 
##D ## run standard
##D Age <- AgeS_Computation(
##D   DATA = Data,
##D   Nb_sample = Nb_sample,
##D   SampleNames = c("GDB5","GDB3"),
##D   PriorAge = rep(c(1,100), 2),
##D   StratiConstraints = SC,
##D   Iter = 100,
##D   quiet = FALSE,
##D   jags_method = "rjags"
##D )
##D 
##D ## extend model
##D Age_extended <- AgeS_Computation(
##D   DATA = Age,
##D   Nb_sample = Nb_sample,
##D   SampleNames = c("GDB5","GDB3"),
##D   PriorAge = rep(c(1,100), 2),
##D   StratiConstraints = SC,
##D   adapt = 0,
##D   burnin = 500,
##D   Iter = 1000,
##D   quiet = FALSE,
##D   jags_method = "rjags"
##D )
##D 
##D ## autorun mode
##D Age <- AgeS_Computation(
##D   DATA = Data,
##D   Nb_sample = Nb_sample,
##D   SampleNames = c("GDB5","GDB3"),
##D   PriorAge = rep(c(1,100), 2),
##D   StratiConstraints = SC,
##D   Iter = 10000,
##D   quiet = FALSE,
##D   jags_method = "rjags",
##D   autorun = TRUE)
##D 
##D ## parallel mode
##D Age <- AgeS_Computation(
##D   DATA = Data,
##D   Nb_sample = Nb_sample,
##D   SampleNames = c("GDB5","GDB3"),
##D   PriorAge = rep(c(1,100), 2),
##D   StratiConstraints = SC,
##D   Iter = 10000,
##D   quiet = FALSE,
##D   jags_method = "rjparallel")
## End(Not run)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("AgeS_Computation", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Age_Computation")
### * Age_Computation

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Age_Computation
### Title: Bayesian analysis for the OSL age estimation of one sample
### Aliases: Age_Computation

### ** Examples

## load data file generated by the function Generate_DataFile
data(DATA1,envir = environment())
priorage <- c(10,60) # GDB3 is an old sample
Age <- Age_Computation(
 DATA = DATA1,
 SampleName = "GDB3",
 PriorAge = priorage,
 Iter = 100,
 quiet = TRUE)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Age_Computation", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Age_OSLC14")
### * Age_OSLC14

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Age_OSLC14
### Title: Bayesian analysis for age estimation of OSL measurements and
###   C-14 ages of various samples
### Aliases: Age_OSLC14

### ** Examples

## Load data
# OSL data
data(DATA1,envir = environment())
data(DATA2,envir = environment())
Data <- combine_DataFiles(DATA2,DATA1)

# 14C data
C14Cal <- DATA_C14$C14[1,1]
SigmaC14Cal <- DATA_C14$C14[1,2]
Names <- DATA_C14$Names[1]

# Prior Age
prior <- rep(c(1,60),3)
samplenature <- matrix(
 data = c(1,0,1,0,1,0),
 ncol = 3,
 nrow = 2,
 byrow = TRUE)

SC <- matrix(
 data = c(1,1,1,0,1,1,0,0,1,0,0,0),
 ncol = 3,
 nrow =4 ,
 byrow = TRUE)

## Age computation of samples
## Not run: 
##D Age <- Age_OSLC14(
##D  DATA = Data,
##D  Data_C14Cal = C14Cal,
##D  Data_SigmaC14Cal = SigmaC14Cal,
##D  SampleNames = c("GDB5",Names,"GDB3"),
##D  Nb_sample = 3,
##D  SampleNature = samplenature,
##D  PriorAge = prior,
##D  StratiConstraints = SC,
##D  Iter = 20,
##D  burnin = 20,
##D  adapt = 20,
##D  n.chains = 2)
## End(Not run)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Age_OSLC14", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("DATA1")
### * DATA1

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: DATA1
### Title: DATA of sample named GDB3
### Aliases: DATA1
### Keywords: datasets

### ** Examples

data(DATA1)
str(DATA1)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("DATA1", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("DATA2")
### * DATA2

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: DATA2
### Title: DATA on sample named GDB5
### Aliases: DATA2
### Keywords: datasets

### ** Examples

data(DATA2)
str(DATA2)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("DATA2", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("DATA3")
### * DATA3

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: DATA3
### Title: DATA of sample named FER1
### Aliases: DATA3
### Keywords: datasets

### ** Examples

data(DATA3)
str(DATA3)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("DATA3", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("DATA_C14")
### * DATA_C14

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: DATA_C14
### Title: C14 cal age estiamte and its error
### Aliases: DATA_C14
### Keywords: datasets

### ** Examples

data(DATA_C14)
(DATA_C14)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("DATA_C14", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Generate_DataFile-deprecated")
### * Generate_DataFile-deprecated

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Generate_DataFile-deprecated
### Title: Generates, from one (or several) BIN-file(s) of Single-grain OSL
###   measurements, a list of luminescence data and information before
###   statistical analysis (DEPRECATED)
### Aliases: Generate_DataFile-deprecated Generate_DataFile

### ** Examples


## Not run: 
##D ## Example for one sample with one Bin File
##D path<- system.file("extdata/samp1", "", package="BayLum")
##D folder=""
##D nbsample=1  # give the number of sample
##D Data <- Generate_DataFile(
##D  Path = path,
##D  FolderNames = folder,
##D  Nb_sample = nbsample,
##D  verbose = FALSE)
##D str(Data)
##D 
##D ## to save information in RData object in folder containing bin file
##D # save(Data,file=c(paste(path,folder,'Data.RData',sep="")))
##D ## to load information containing Data.RData object
##D # load(file=c(paste(path,folder,"Data.RData",sep="")))
## End(Not run)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Generate_DataFile-deprecated", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Generate_DataFile_MG-deprecated")
### * Generate_DataFile_MG-deprecated

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Generate_DataFile_MG-deprecated
### Title: Generates, from one (or several) BIN file(s) of Multi-grain OSL
###   measurements a list of luminescence data and information before
###   statistical analysis (DEPRECATED)
### Aliases: Generate_DataFile_MG-deprecated Generate_DataFile_MG

### ** Examples

## Not run: 
##D path <- system.file("extdata/FER1", "", package="BayLum")
##D folder <- ""
##D # give the number of sample
##D nbsample <- 1
##D DATA <- Generate_DataFile_MG(
##D  Path = path,
##D  FolderNames = folder,
##D  Nb_sample = nbsample)
##D str(DATA)
##D 
##D # to save information in RData object in folder containing bin file
##D #save(DATA,file=c(paste(path,folder,'DATA.RData',sep="")))
##D # to load information containing DATA.RData object
##D #load(file=c(paste(path,folder,"DATA.RData",sep="")))
## End(Not run)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Generate_DataFile_MG-deprecated", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("IntCal13")
### * IntCal13

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: IntCal13
### Title: Atmospheric North data for calibration of 14C age
### Aliases: IntCal13
### Keywords: datasets

### ** Examples

data(IntCal13)
## maybe str(IntCal13) ; head(IntCal13) ...



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("IntCal13", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("IntCal20")
### * IntCal20

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: IntCal20
### Title: Atmospheric North data for calibration of 14C age
### Aliases: IntCal20
### Keywords: datasets

### ** Examples

data(IntCal20)
## maybe str(IntCal20) ; head(IntCal20) ...



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("IntCal20", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("LT_RegenDose-deprecated")
### * LT_RegenDose-deprecated

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: LT_RegenDose-deprecated
### Title: Plots Lx/Tx as a function of the regenerative dose (DEPRECATED)
### Aliases: LT_RegenDose-deprecated LT_RegenDose

### ** Examples

## Not run: 
##D ## load data file generated by the function Generate_DataFile
##D data(DATA3,envir = environment())
##D path<- system.file("extdata/FER1", "", package="BayLum")
##D folder=""
##D samplename <- "FER1"
##D LT_RegenDose(
##D  DATA = DATA3,
##D  Path = path,
##D  FolderNames = folder,
##D  SampleNames = samplename,
##D  Nb_sample = 1,
##D  SG = FALSE)
## End(Not run)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("LT_RegenDose-deprecated", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("MCMCsample")
### * MCMCsample

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: MCMCsample
### Title: MCMC sample from the posterior distribution of the dataset GDB5
### Aliases: MCMCsample
### Keywords: datasets

### ** Examples

data(MCMCsample)
## maybe str(MCMCsample) ; plot(MCMCsample[,1],type="l") ...



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("MCMCsample", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Marine13")
### * Marine13

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Marine13
### Title: Marine data for calibration of 14C age
### Aliases: Marine13
### Keywords: datasets

### ** Examples

data(Marine13)
## maybe str(Marine13) ; head(Marine13) ...



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Marine13", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Marine20")
### * Marine20

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Marine20
### Title: Marine data for calibration of 14C age
### Aliases: Marine20
### Keywords: datasets

### ** Examples

data(Marine20)
## maybe str(Marine20) ; head(Marine20) ...



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Marine20", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("ModelC14")
### * ModelC14

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: ModelC14
### Title: Likelihood of C14 samples for JAGS models use in 'Age_OSLC14'
### Aliases: ModelC14
### Keywords: datasets

### ** Examples

data(Model_AgeC14)
writeLines(Model_AgeC14$full)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("ModelC14", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("ModelOSL")
### * ModelOSL

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: ModelOSL
### Title: Likelihood of OSL samples for JAGS models use in 'Age_OSLC14'
### Aliases: ModelOSL
### Keywords: datasets

### ** Examples

data(ModelOSL)
## The JAGS model of the likelyhood for a saturating exponential plus linear growth
## (a function of the type \code{f(x)=a(1-exp(-x/b))+cx+d})
## and a gaussian distribution of equivalent doses around the palaeodose:
writeLines(ModelOSL$AgesMultiOSL_EXPLIN$gaussian)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("ModelOSL", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("ModelPrior")
### * ModelPrior

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: ModelPrior
### Title: Prior for JAGS models use in 'Age_OSLC14'
### Aliases: ModelPrior
### Keywords: datasets

### ** Examples

data(ModelPrior)
## ModelPrior[[OSL]]
writeLines(ModelPrior$OSL)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("ModelPrior", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Model_Age")
### * Model_Age

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Model_Age
### Title: JAGS models use in 'Age_Computation'
### Aliases: Model_Age
### Keywords: datasets

### ** Examples

data(Model_Age)
## Terminal print
## The JAGS model for a saturating exponential plus linear growth
## (a function of the type \code{f(x)=a(1-exp(-x/b))+cx+d})
## and a gaussian distribution of equivalent doses around the palaeodose:
writeLines(Model_Age$AgeMultiBF_EXPLIN$cauchy)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Model_Age", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Model_AgeC14")
### * Model_AgeC14

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Model_AgeC14
### Title: JAGS models use in 'AgeC14_Computation'
### Aliases: Model_AgeC14
### Keywords: datasets

### ** Examples

data(Model_AgeC14)
writeLines(Model_AgeC14$full)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Model_AgeC14", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Model_AgeS")
### * Model_AgeS

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Model_AgeS
### Title: JAGS models use in 'AgeS_Computation'
### Aliases: Model_AgeS
### Keywords: datasets

### ** Examples

data(Model_AgeS)
## The JAGS model for a saturating exponential plus linear growth
## (a function of the type \code{f(x)=a(1-exp(-x/b))+cx+d})
## and a gaussian distribution of equivalent doses around the palaeodose:
writeLines(Model_AgeS$AgesMultiCS2_EXP$gaussian)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Model_AgeS", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Model_Palaeodose")
### * Model_Palaeodose

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Model_Palaeodose
### Title: JAGS models use in 'Palaeodose_Computation'
### Aliases: Model_Palaeodose
### Keywords: datasets

### ** Examples

data(Model_Palaeodose)
writeLines(Model_Palaeodose$PalaeodosesMultiBF_EXPLIN$gaussian)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Model_Palaeodose", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("Palaeodose_Computation")
### * Palaeodose_Computation

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: Palaeodose_Computation
### Title: Bayesian analysis for the palaeodose estimation of various
###   samples
### Aliases: Palaeodose_Computation

### ** Examples

## Load data
data(DATA1,envir = environment())
## Palaeodose computation of samples GDB3
P=Palaeodose_Computation(DATA=DATA1,Nb_sample=1,SampleNames=c("GDB5"),Iter=100)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("Palaeodose_Computation", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("SCMatrix")
### * SCMatrix

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: SCMatrix
### Title: Construct the Stratigraphic Constrain Matrix Interactively
### Aliases: SCMatrix

### ** Examples

## Not run: 
##D SCMatrix(
##D  Nb_sample = 2,
##D  SampleNames = c("sample1","sample2"))
## End(Not run)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("SCMatrix", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("SC_Ordered")
### * SC_Ordered

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: SC_Ordered
### Title: Create Stratigraphically Ordered Sample Matrix
### Aliases: SC_Ordered
### Keywords: datagen

### ** Examples

SC <- SC_Ordered(Nb_sample = 3)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("SC_Ordered", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("SHCal13")
### * SHCal13

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: SHCal13
### Title: Atmospheric South data for calibration of 14C age
### Aliases: SHCal13
### Keywords: datasets

### ** Examples

data(SHCal13)
## maybe str(SHCal13) ; head(SHCal13) ...



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("SHCal13", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("SHCal20")
### * SHCal20

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: SHCal20
### Title: Atmospheric South data for calibration of 14C age
### Aliases: SHCal20
### Keywords: datasets

### ** Examples

data(SHCal20)
## maybe str(SHCal20) ; head(SHCal20) ...



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("SHCal20", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("combine_DataFiles")
### * combine_DataFiles

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: combine_DataFiles
### Title: Combine objects
### Aliases: combine_DataFiles Concat_DataFile

### ** Examples

# load data files
data(DATA1,envir = environment())
data(DATA2,envir = environment())

#combine objects
DATA3 <- combine_DataFiles(DATA1, DATA2)
str(DATA3)



base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("combine_DataFiles", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("create_DataFile")
### * create_DataFile

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: create_DataFile
### Title: Prepare input data for subsequent BayLum Analysis
### Aliases: create_DataFile

### ** Examples

##set path to YAML file
yaml_file <- system.file("extdata/example.yml", package = "BayLum")

samp1_file <- system.file("extdata/samp1/bin.bin", package = "BayLum")
samp2_file <- system.file("extdata/samp2/bin.bin", package = "BayLum")

## import BIN files
samp1 <- Luminescence::read_BIN2R(samp1_file, verbose = FALSE) |>
 subset(POSITION == 2 & GRAIN == 32)
samp2 <- Luminescence::read_BIN2R(samp2_file, verbose = FALSE) |>
 subset(POSITION == 2 & GRAIN == 32)

## create file
create_DataFile(yaml_file)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("create_DataFile", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("create_FolderTemplates")
### * create_FolderTemplates

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: create_FolderTemplates
### Title: Create Folder Templates
### Aliases: create_FolderTemplates
### Keywords: IO datagen

### ** Examples

create_FolderTemplates(tempdir())





base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("create_FolderTemplates", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("create_ThetaMatrix")
### * create_ThetaMatrix

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: create_ThetaMatrix
### Title: Create Theta Matrix
### Aliases: create_ThetaMatrix
### Keywords: IO datagen

### ** Examples

##(1) return template data.frame (no file output)
create_ThetaMatrix()

## Not run: 
##D ##(2) return template as data.frame + file
##D file_path <- tempfile(fileext = ".csv")
##D create_ThetaMatrix(output_file = file_path )
##D 
##D ##NOT RUNNING EXAMPLE for sigma_s
##D calc_ThetaMatrix(...,
##D sigma_s =  c(
##D  s_betaK = 0.010,
##D  s_betaU = 0.007,
##D  s_betaTh = 0.006,
##D  s_gammaK = 0.010,
##D  s_gammaU = 0.007,
##D  s_gammaTh = 0.006,
##D  s_gammaDR = 0.05,
##D  s_CAL = 0.020,
##D  s_intDR = 0.030))
##D 
## End(Not run)






base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("create_ThetaMatrix", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("plot_Ages")
### * plot_Ages

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: plot_Ages
### Title: Create Age Plot
### Aliases: plot_Ages

### ** Examples

## load data
data(DATA_C14,envir = environment())
C14Cal <- DATA_C14$C14[,1]
SigmaC14Cal <- DATA_C14$C14[,2]
Names <- DATA_C14$Names
nb_sample <- length(Names)

## Age computation
Age <- AgeC14_Computation(
   Data_C14Cal = C14Cal,
   Data_SigmaC14Cal = SigmaC14Cal,
   SampleNames = Names,
   Nb_sample = nb_sample,
   PriorAge = rep(c(20,60),nb_sample),
   Iter = 500,
   quiet = TRUE)

## plot output
plot_Ages(Age)

## plot output
plot_Ages(Age, plot_mode = "density")




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("plot_Ages", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("plot_MCMC")
### * plot_MCMC

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: plot_MCMC
### Title: Plot MCMC trajectories and posterior distributions
### Aliases: plot_MCMC
### Keywords: dplot

### ** Examples

data(MCMCsample,envir = environment())
object <- coda::as.mcmc(MCMCsample)
plot_MCMC(object)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("plot_MCMC", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("plot_RegDosePoints")
### * plot_RegDosePoints

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: plot_RegDosePoints
### Title: Plot Regeneration Dose Points
### Aliases: plot_RegDosePoints

### ** Examples


data(DATA3,envir = environment())
plot_RegDosePoints(DATA3)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("plot_RegDosePoints", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("plot_Scatterplots")
### * plot_Scatterplots

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: plot_Scatterplots
### Title: Display Scatter Plot Matrix of the Bayesian Age Results
### Aliases: plot_Scatterplots ScatterSamples

### ** Examples

data(AgeS,envir = environment())

##hexbin
plot_Scatterplots(
   object = AgeS$Sampling,
   sample_names = c("GDB5", "GDB3"),
   sample_selection = c(1,2)
 )

##scatter smooth (matrix)
plot_Scatterplots(
   object = AgeS$Sampling,
   sample_names = c("GDB5", "GDB3"),
   sample_selection = c(1,2),
   plot_type = "smoothScatter")


##scatter smooth (single)
plot_Scatterplots(
   object = AgeS$Sampling,
   sample_names = c("GDB5", "GDB3"),
   sample_selection = c(1,2),
   plot_type = "smoothScatter",
   plot_mode = "single")




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("plot_Scatterplots", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("write_BayLumFiles")
### * write_BayLumFiles

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: write_BayLumFiles
### Title: Write BayLum .csv-files
### Aliases: write_BayLumFiles
### Keywords: IO datagen

### ** Examples

# example samples
SampleNames <- c("OSL-1-MG","OSL-2-SG")

# number of .bin-files for each sample
BinPerSample <- c(1,3)

# List of data.frames of accepted aliquot/grain to be included
# in the analysis for each .bin-file.
DiscPos <- list(
data.frame("position" = 1:48),
data.frame("position" = c(1,1,1,1), "grain" = c(4,67,92,99)),
data.frame("position" = c(2,2,2,2), "grain" = c(7,13,41,72)),
data.frame("position" = c(3,3,3,3), "grain" = c(7,52,67,88)))

# example 1: write to disk (all together)
write_BayLumFiles(
folder = paste(tempdir(),"new_BayLum_folder",sep = "/"),
SampleNames = SampleNames,
BinPerSample = BinPerSample,
DiscPos = DiscPos,
DRenv = c(1.75, 1.52, 1.52, 1.52),
DRenv.error = c(0.04, 0.03, 0.03, 0.03),
DRsource = c(0.2075, 0.1501, 0.1501, 0.1501),
DRsource.error = c(0.0010, 0.0008, 0.0008, 0.0008))

# example 2: write to disk (by sample)
write_BayLumFiles(
folder = paste(tempdir(),"new_BayLum_folder",sep = "/"),
SampleNames = "OSL-1-MG",
BinPerSample = 1,
DiscPos = DiscPos[[1]],
DRenv = 1.75,
DRenv.error = 0.04,
DRsource = 0.2075,
DRsource.error = 0.0010)

write_BayLumFiles(
folder = paste(tempdir(),"new_BayLum_folder",sep = "/"),
SampleNames = "OSL-2-SG",
BinPerSample = 3,
DiscPos = DiscPos[2:4],
DRenv = 1.75,
DRenv.error = 0.04,
DRsource = 0.2075,
DRsource.error = 0.0010)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("write_BayLumFiles", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
cleanEx()
nameEx("write_YAMLConfigFile")
### * write_YAMLConfigFile

flush(stderr()); flush(stdout())

base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: write_YAMLConfigFile
### Title: Write Auto Generated YAML BayLum Configuration File to the Disc
### Aliases: write_YAMLConfigFile

### ** Examples


## generate list
write_YAMLConfigFile(
sample = c("samp1", "samp2"),
settings.rules.endTest = 10)

## generate file (here written in tempdir)
write_YAMLConfigFile(
 output_file = tempfile("configuration.yml"),
 sample = c("samp1", "samp2"),
 settings.rules.endTest = 10)




base::assign(".dptime", (proc.time() - get(".ptime", pos = "CheckExEnv")), pos = "CheckExEnv")
base::cat("write_YAMLConfigFile", base::get(".format_ptime", pos = 'CheckExEnv')(get(".dptime", pos = "CheckExEnv")), "\n", file=base::get(".ExTimings", pos = 'CheckExEnv'), append=TRUE, sep="\t")
### * <FOOTER>
###
cleanEx()
options(digits = 7L)
base::cat("Time elapsed: ", proc.time() - base::get("ptime", pos = 'CheckExEnv'),"\n")
grDevices::dev.off()
###
### Local variables: ***
### mode: outline-minor ***
### outline-regexp: "\\(> \\)?### [*]+" ***
### End: ***
quit('no')
