---
title: "How to Analyse Al$_{2}$O$_{3}$:C Measurements"
author: "Sebastian Kreutzer"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    fig_caption: yes
    highlight: tango
    number_sections: yes
    toc: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

# Scope
The package 'Luminescence' offers three distinct functions dealing with the analysis of Al$_{2}$O$_{3}$:C pellet measurements:

1. `analyse_Al2O3C_ITC()`
2. `analyse_Al2O3C_CrossTalk()`
3. `analyse_Al2O3C_Measurement()`

Only the last function is really needed to routinely estimate the (environmental $\gamma$-) dose the pellet had received. However, the first two functions are needed to determine and later correct for equipment related issues. If you have already performed the
first two analysis or you do not feel the need for them, you can direclty start with the last section.

The following tutorial assumes that all measurements have been performed on a Freiberg Instruments *lexsyg SMART* luminescence reader (Richter et al., 2015). However, the general procedure should work also for a Risø TL/OSL reader. 

Please further note that this vignette covers only the **R** releated part of the data analysis and will 
not explain the theoretical and physical background. Please see XXXX for details. 

# Determine irradiation time correction factors

To determine the irradiation time correction factors the function `analyse_Al2O3C_ITC()` is used. 

# Estimate irradiation crosstalk

# Al$_{2}$O$_{3}$:C dose determination

# Ease your workflow

# References

Richter, D., Richter, A., Dornich, K., 2015. Lexsyg smart — a luminescence detection system for dosimetry, material research and dating application. Geochronometria 42, 202–209. doi:10.1515/geochr-2015-0022
