## About this app

This software provides a graphical user interface to the R package 'RCarb'.

**Version**: 0.1.0 [2018-10-14]

**Author**: Sebastian Kreutzer, IRAMAT-CRP2A, UMR 5060, CNRS - Université Bordeaux Montaigne (France)

**Contact**: sebastian.kreutzer@u-bordeaux-montaigne.fr

## References to cite

### Underlying R package

Kreutzer, S., Nathan, R.P., Mauz, B., 2018. RCarb: Dose Rate Modelling of Carbonate-Rich
Samples. R package version 0.1.2. https://CRAN.R-project.org/package=RCarb

### Background modelling

Mauz, B., Hoffmann, D., 2014. What to do when carbonate replaced water: Carb, the model for estimating the dose rate of carbonate-rich samples. Ancient TL 32, 24–32. http://ancienttl.org/ATL_32-2_2014/ATL_32-2_Mauz_p24-32.pdf

Nathan, R.P., Mauz, B., 2008. On the dose-rate estimate of carbonate-rich sediments for trapped charge dating. Radiation Measurements 43, 14–25. doi: [10.1016/j.radmeas.2007.12.012](https://dx.doi.org/10.1016/j.radmeas.2007.12.012)


## Licence

This program is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU [General Public License](https://www.gnu.org/licenses/gpl-3.0.en.html) for more details
