# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.set_ODE_Rcpp <- function(t, n, parameters) {
    .Call(`_RLumModel_set_ODE_Rcpp`, t, n, parameters)
}

.set_ODE_Rcpp_LM_OSL <- function(t, n, parameters) {
    .Call(`_RLumModel_set_ODE_Rcpp_LM_OSL`, t, n, parameters)
}

