// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// analyse_IRSARRF_SRS
RcppExport SEXP analyse_IRSARRF_SRS(NumericVector values_regenerated_limited, NumericVector values_natural_limited, int n_MC);
RcppExport SEXP Luminescence_analyse_IRSARRF_SRS(SEXP values_regenerated_limitedSEXP, SEXP values_natural_limitedSEXP, SEXP n_MCSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type values_regenerated_limited(values_regenerated_limitedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type values_natural_limited(values_natural_limitedSEXP);
    Rcpp::traits::input_parameter< int >::type n_MC(n_MCSEXP);
    __result = Rcpp::wrap(analyse_IRSARRF_SRS(values_regenerated_limited, values_natural_limited, n_MC));
    return __result;
END_RCPP
}
// create_UID
CharacterVector create_UID();
RcppExport SEXP Luminescence_create_UID() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(create_UID());
    return __result;
END_RCPP
}
